/**
 * Renderer — transforms `FileClosureSet[]` into the deterministic
 * markdown block that lives between the `<!-- amdu:begin -->` and
 * `<!-- amdu:end -->` markers in `AGENTS.md`.
 *
 * The output format mirrors the `@workspace/bindings/zellij/` convention:
 * a section heading per file, and for each extracted closure a short JSDoc
 * blurb (if any) immediately followed by a fenced TypeScript block
 * containing its printed signature.
 *
 * @since 0.1.0
 */

import { Context, Effect, Layer, Order } from 'effect';
import * as Arr from 'effect/Array';
import * as Str from 'effect/String';

import type { ClosureRecord, FileClosureSet } from './Closure.ts';

// ───────────────────────────────────────────────────────────────────────────
// Markers
// ───────────────────────────────────────────────────────────────────────────

/**
 * Opening marker inserted into `AGENTS.md`. Everything above this line is
 * treated as manual prose and preserved verbatim across `amdu sync`.
 *
 * @category Constants
 * @since 0.1.0
 */
export const BEGIN_MARKER = '<!-- amdu:begin -->';

/**
 * Closing marker inserted into `AGENTS.md`. Everything below this line is
 * treated as manual prose and preserved verbatim across `amdu sync`.
 *
 * @category Constants
 * @since 0.1.0
 */
export const END_MARKER = '<!-- amdu:end -->';

// ───────────────────────────────────────────────────────────────────────────
// Service
// ───────────────────────────────────────────────────────────────────────────

/**
 * Capability surface of {@link Service}.
 *
 * @category Models
 * @since 0.1.0
 */
export interface Interface {
	/**
	 * Render a managed `AGENTS.md` block for the given file closure sets.
	 *
	 * Output is a single string starting with {@link BEGIN_MARKER} and
	 * ending with {@link END_MARKER}. File sets are emitted in input
	 * order; closures within each file are emitted in source order.
	 */
	readonly render: (
		files: ReadonlyArray<FileClosureSet>
	) => Effect.Effect<string>;
}

/**
 * The `Renderer` service identity.
 *
 * @category Service
 * @since 0.1.0
 */
export class Service extends Context.Service<Service, Interface>()(
	'agentsmd-undriftable/Renderer'
) {}

// ───────────────────────────────────────────────────────────────────────────
// Helpers
// ───────────────────────────────────────────────────────────────────────────

const orderByLine = Order.mapInput(
	Order.Number,
	(record: ClosureRecord) => record.line
);

const kindLabel = (record: ClosureRecord): string => {
	const prefix = record.exported ? 'export ' : '';
	return `${prefix}${record.kind}`;
};

const qualifiedName = (record: ClosureRecord): string =>
	record.scope.length === 0 ? record.name : `${record.scope}.${record.name}`;

const renderClosure = (record: ClosureRecord): string => {
	const lines: Array<string> = [];
	lines.push(`#### \`${qualifiedName(record)}\` — \`${kindLabel(record)}\``);
	lines.push('');
	const trimmedDoc = Str.trim(record.jsdoc);
	if (trimmedDoc.length !== 0) {
		lines.push(trimmedDoc);
		lines.push('');
	}
	lines.push('```ts');
	lines.push(record.signature);
	lines.push('```');
	return lines.join('\n');
};

const renderFile = (file: FileClosureSet): string => {
	const header = `### \`${file.relativePath}\``;
	return Arr.match(file.closures, {
		onEmpty: () =>
			[header, '', '_(no top-level declarations found)_', ''].join('\n'),
		onNonEmpty: (records) => {
			const ordered = Arr.sort(records, orderByLine);
			const blocks = Arr.map(ordered, renderClosure);
			return [header, '', ...Arr.intersperse(blocks, ''), ''].join('\n');
		}
	});
};

const renderBody = (files: ReadonlyArray<FileClosureSet>): string =>
	Arr.match(files, {
		onEmpty: () => '_(no source files found)_\n',
		onNonEmpty: (entries) =>
			[...Arr.map(entries, renderFile), ''].join('\n')
	});

// ───────────────────────────────────────────────────────────────────────────
// Layer
// ───────────────────────────────────────────────────────────────────────────

/**
 * Layer providing the default {@link Service} implementation.
 *
 * @category Layers
 * @since 0.1.0
 */
const PREAMBLE =
	'<!-- This section is generated by `amdu sync`. Manual edits inside will be clobbered; edit above or below the markers instead. -->';

const renderManagedBlock = (files: ReadonlyArray<FileClosureSet>): string =>
	[
		BEGIN_MARKER,
		PREAMBLE,
		'',
		'## Module surface',
		'',
		renderBody(files),
		END_MARKER
	].join('\n');

export const layer: Layer.Layer<Service, never, never> = Layer.succeed(
	Service,
	Service.of({
		render: (files) => Effect.sync(() => renderManagedBlock(files))
	})
);
